### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by eZioPan**
Thank you for your working, here is a Simplified Chinese translation.
I want to fully translate your UI into Chinese, and I hope I can get more UI Element to translate.

### CODE REVIEW

**Comment by Nico-Duduf** [comment]
Hi, many, many thanks for this translation!

I won't merge this pull request yet, because I've planned working on a translation tool for the upcoming Duik 15, I'll include your translations when it's done ;)

This tool will be designed to make it easier for end users to add and share their own translations.

**Comment by eZioPan** [comment]
Thank you for reply!
I find out that my translation is based on DuIK14, and some documents are changed in DuIK15.
So I will close this pull request and wait for your translation tool or newer Duik_translations.jsxinc file.
If you finish your tool or something else, please remind me, and I will do my best to make DuIK better!

**Comment by Nico-Duduf** [comment]
Hi,
I just updated the translation system for Duik.

To update translations, you now have to edit the translation file of the language you want to add/update,
all translations yet to do are located in the "unfinished translations" folder I just created.
I already created a simplified chinese file:
https://github.com/Duduf-dev/Duik/blob/master/Unfinished%20Translations/Duik_translations_zh.jsxinc
All you have to do is add the translations in each Array, in the empty strings, being careful not to modify the english strings and the numbers (they are used to locate the corresponding translation, it makes it easier to use inside Duik).
You can have a look in the French translation which is already complete as a reference.

I'm going to develop an editor to edit those translations files more easily, but I do not know when I will have time to finish it.

**Comment by Nico-Duduf** [comment]
I forgot to explain:
Duik now automatically looks for translation files at launch, which makes it possible to easily add (or remove) any language ; the editor I'll develop will be able to create/update new translation files automatically, grabbing the strings from Duik itself or any existing translation.

**Pull request closed without merging**
